version: '3.9'

services:
  # Main Web Service
  # PHP, Nginx Web Server
  web:
    image: trafex/php-nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./web/html:/var/www/html"
      - "./cfg/nginx:/etc/nginx/conf.d"
      - "./cfg/php-fpm-settings:/etc/php83/php-fpm.d"
    depends_on:
      backend:
        condition: service_started
        restart: true
  # Main Backend API
  # Python
  backend:
    image: munchmunch/backend
    build:
      context: api
      dockerfile: ./DOCKERFILE
    depends_on:
      main_database:
        condition: service_healthy
        restart: true
      s3storage:
        condition: service_healthy
        restart: true
      post_database:
        condition: service_healthy
        restart: true
    volumes:
      - "./api:/app"
    ports:
      - 5069:5000
    env_file: ".env"
  # Relational Database
  # Postgresql (Users, other basic information)
  main_database:
    image: postgres:16
    restart: always
    shm_size: 128mb
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  # NoSQL Database
  # MongoDB (Post, and other block data)
  post_database:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - "./data/mongodb:/data/db"
    env_file: ".env"
    healthcheck: 
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 20s
  # Postgresql Web UI
  # Used for viewing and modifying data within postgres.
  main_database_ui:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      main_database:
          condition: service_healthy
          restart: true
    volumes:
      - type: bind
        source: "./cfg/pgadmin/preferences.json"
        target: "/pgadmin4/preferences.json"
      - type: bind
        source: "./cfg/pgadmin/servers.json"
        target: "/pgadmin4/servers.json"
    env_file: ".env"
    ports:
      - "6969:80"
  # MongoDB Web UI
  # Used for viewing and modifying data within mongo. 
  post_database_ui:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      post_database:
          condition: service_healthy
          restart: true
    ports:
      - 8082:8081
    env_file: ".env"
  # S3 Object storage
  # Used for profile pictures, recipe pictures/videos, and other files that need to be shared.
  s3storage:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: ".env"
    volumes:
      - "./data/minio/data:/data"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
